export const environment = {
    production: false,
    title: `${PROGRAM_TITLE}`,
     BASE_URL: `${BASE_URL}`,
    SONG_EXT: `${SONG_EXT}`,
    SHOW_EXT: `${SHOW_EXT}`,
    PATRON_EXT: `${PATRON_EXT}`,
    SETLIST_EXT: `${SETLIST_EXT}`,
    SUBSCRIBE_EXT: `${SUBSCRIBE_EXT}`,
    REQUEST_EXT: `${REQUEST_EXT}`,
    URL_SUFFIX: `${URL_SUFFIX}`,
    LOG_ENDPOINT: `${LOG_ENDPOINT}`,
    IP_GEOLOCATION_ENDPOINT: '${IP_GEOLOCATION_ENDPOINT}',
    IP_GEOLOCATION_API_KEY: '${IP_GEOLOCATION_API_KEY}'
  };